version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    restart: always
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80" # Expose frontend on port 80
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:

volumes:
  pgdata:
