# Production Docker Compose configuration
# docker-compose -f docker-compose.yml up --build -d

services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "4000:4000"
    command: npm start # Use production command
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:4000
    ports:
      - "3000:3000"
    command: serve -s dist -l 3000 # Serve the static build with `serve` or another static file server
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
